name: Metrics
on:
  # daily cron schedule (midnight stockholm time cuz actions run with UTC timezone)
  schedule: [{cron: "0 1 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ secrets.STEAM }}
          plugin_steam: yes
          plugin_steam_user: "76561198256785048"
          plugin_steam_sections: recently-played
          plugin_steam_achievements_limit: 0
          plugin_steam_recent_games_limit: 3
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.music.recent.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_time_range: medium
          plugin_music_top_type: tracks
          plugin_music_token: ${{ secrets.SPOTIFY }}
          plugin_music_limit: 7
